#!/bin/bash

# Copyright 2017 Capsule8, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CAPSULE8_DIR="$(git rev-parse --show-toplevel)"
WORK_DIR="/go/src/github.com/capsule8/capsule8"
MAKE_STR="make -j4"

if [ -z "${VERSION}" ]; then
    VERSION="$(git describe --abbrev=0 --tags 2>/dev/null)"
fi
if [ -z "${GIT_SHA}" ]; then
    GIT_SHA="$(git describe --match=NeVeRmAtCh --always --abbrev=7 --dirty)"
fi

docker build -t capsule8_builder -f Dockerfile.builder "${CAPSULE8_DIR}/vendor"

docker run -it --rm \
        -e VERSION="${VERSION}+${GIT_SHA}" \
        -v "${CAPSULE8_DIR}":"${WORK_DIR}" \
        -w "${WORK_DIR}" \
        capsule8_builder \
        /bin/bash -c "${MAKE_STR} $*"
