// Copyright 2017 Capsule8, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sensor

import (
	"fmt"
	"time"

	"github.com/capsule8/capsule8/pkg/expression"
)

// TickerEventTypes defines the field types that can be used with filters on
// ticker telemetry events.
var TickerEventTypes = expression.FieldTypeMap{
	"seconds":     expression.ValueTypeSignedInt64,
	"nanoseconds": expression.ValueTypeSignedInt64,
}

// TickerTelemetryEvent is a telemetry event generated by the ticker event
// source.
type TickerTelemetryEvent struct {
	TelemetryEventData

	Seconds     int64
	Nanoseconds int64
}

// CommonTelemetryEventData returns the telemtry event data common to all
// telemetry events for a chargen telemetry event.
func (e TickerTelemetryEvent) CommonTelemetryEventData() TelemetryEventData {
	return e.TelemetryEventData
}

func (s *Subscription) dispatchTickerEvent(
	eventid uint64,
	data expression.FieldValueMap,
) {
	var e TickerTelemetryEvent

	e.Init(s.sensor)
	e.Seconds = data["seconds"].(int64)
	e.Nanoseconds = data["nanoseconds"].(int64)
	s.DispatchEvent(eventid, e, data)
}

// RegisterTickerEventFilter registers a ticker event filter with a
// subscription.
func (s *Subscription) RegisterTickerEventFilter(
	interval int64,
	filter *expression.Expression,
) {
	if interval <= 0 {
		s.logStatus(
			fmt.Sprintf("Invalid ticker interval: %d", interval))
		return
	}

	monitor := s.sensor.Monitor()
	eventID := monitor.ReserveEventID()

	done := make(chan struct{})

	es, err := s.addEventSink(eventID, filter)
	if err != nil {
		s.logStatus(
			fmt.Sprintf("Invalid filter expression for ticker filter: %v", err))
		return
	}
	es.unregister = func(es *eventSink) {
		close(done)
	}
	es.enable = func() {
		go func() {
			ticker := time.NewTicker(time.Duration(interval))
			for {
				select {
				case <-done:
					ticker.Stop()
					return
				case <-ticker.C:
					now := time.Now()
					data := expression.FieldValueMap{
						"seconds":     int64(now.Unix()),
						"nanoseconds": int64(now.UnixNano()),
					}
					s.dispatchTickerEvent(eventID, data)
				}
			}
		}()
	}
}
